spring.application.name=performence-tuning

# 1. Thông tin kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình Connection Pool (HikariCP) tối ưu cho việc insert dữ liệu lớn
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
